-- MySQL Script generated by MySQL Workbench
-- 04/02/19 01:50:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bbwatch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bbwatch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbwatch` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bbwatch` ;

-- -----------------------------------------------------
-- Table `bbwatch`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Usuario` (
  `id_usuario` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `chave` VARCHAR(100) NOT NULL COMMENT '',
  `data_cadastro` DATETIME NOT NULL COMMENT '',
  `ativo` TINYINT(1) NOT NULL COMMENT '',
  `rg` VARCHAR(15) NOT NULL COMMENT '',
  `especialidade` VARCHAR(45) NULL COMMENT '',
  `crm` INT NULL COMMENT '',
  `data_nascimento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Contato` (
  `id_contato` INT NOT NULL COMMENT '',
  `telefone_celular` INT NULL COMMENT '',
  `telefone_residencial` INT NULL COMMENT '',
  `telefone_comercial` INT NULL COMMENT '',
  `email` VARCHAR(50) NOT NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_contato`)  COMMENT '',
  UNIQUE INDEX `idContato_UNIQUE` (`id_contato` ASC)  COMMENT '',
  INDEX `fk_Contato_Usuario_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Contato_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bbwatch`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Permissao` (
  `id_permissao` INT NOT NULL COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id_permissao`)  COMMENT '',
  UNIQUE INDEX `idPermissao_UNIQUE` (`id_permissao` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Perfil` (
  `id_perfil` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_perfil`)  COMMENT '',
  UNIQUE INDEX `idPerfil_UNIQUE` (`id_perfil` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Perfil_Permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Perfil_Permissao` (
  `id_perfil` INT NOT NULL COMMENT '',
  `id_permissao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_perfil`, `id_permissao`)  COMMENT '',
  INDEX `fk_Perfil_Permissao_Permissao1_idx` (`id_permissao` ASC)  COMMENT '',
  CONSTRAINT `fk_Perfil_Permissao_Perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `bbwatch`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_Permissao_Permissao1`
    FOREIGN KEY (`id_permissao`)
    REFERENCES `bbwatch`.`Permissao` (`id_permissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Tutorial` (
  `id_tutorial` INT NOT NULL COMMENT '',
  `titulo` VARCHAR(100) NULL COMMENT '',
  `data_criacao` DATETIME NULL COMMENT '',
  `instrucoes` VARCHAR(300) NULL COMMENT '',
  PRIMARY KEY (`id_tutorial`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Acesso_Tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Acesso_Tutorial` (
  `id_usuario` INT NOT NULL COMMENT '',
  `tipo_acesso` VARCHAR(20) NULL COMMENT '',
  `id_tutorial` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`, `id_tutorial`)  COMMENT '',
  INDEX `fk_Acesso_Tutorial_Tutorial1_idx` (`id_tutorial` ASC)  COMMENT '',
  CONSTRAINT `fk_Acesso_Tutorial_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bbwatch`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acesso_Tutorial_Tutorial`
    FOREIGN KEY (`id_tutorial`)
    REFERENCES `bbwatch`.`Tutorial` (`id_tutorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Crianca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Crianca` (
  `id_crianca` INT NOT NULL COMMENT '',
  `nome` VARCHAR(50) NULL COMMENT '',
  `data_nascimento` DATETIME NULL COMMENT '',
  `genero` VARCHAR(10) NULL COMMENT '',
  `peso` TINYINT NULL COMMENT '',
  `altura` TINYINT NULL COMMENT '',
  `tipo_sanguineo` VARCHAR(2) NULL COMMENT '',
  `alergias` VARCHAR(300) NULL COMMENT '',
  `rg` VARCHAR(15) NULL COMMENT '',
  `raca` VARCHAR(10) NULL COMMENT '',
  `cor_cabelo` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`id_crianca`)  COMMENT '',
  UNIQUE INDEX `id_crianca_UNIQUE` (`id_crianca` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Vinculo` (
  `data_vinculo` DATETIME NOT NULL COMMENT '',
  `tipo_vinculo` VARCHAR(45) NOT NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `id_crianca` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`, `id_crianca`)  COMMENT '',
  INDEX `fk_Vinculo_Crianca1_idx` (`id_crianca` ASC)  COMMENT '',
  CONSTRAINT `fk_Vinculo_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bbwatch`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vinculo_Crianca`
    FOREIGN KEY (`id_crianca`)
    REFERENCES `bbwatch`.`Crianca` (`id_crianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Sintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Sintoma` (
  `id_siintoma` INT NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  `data` DATETIME NULL COMMENT '',
  `observacao` VARCHAR(300) NULL COMMENT '',
  `id_crianca` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_siintoma`, `id_crianca`)  COMMENT '',
  UNIQUE INDEX `id_siintoma_UNIQUE` (`id_siintoma` ASC)  COMMENT '',
  INDEX `fk_Sintoma_Crianca1_idx` (`id_crianca` ASC)  COMMENT '',
  CONSTRAINT `fk_Sintoma_Crianca1`
    FOREIGN KEY (`id_crianca`)
    REFERENCES `bbwatch`.`Crianca` (`id_crianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Vacina` (
  `id_vacina` INT NOT NULL COMMENT '',
  `nome` VARCHAR(50) NULL COMMENT '',
  `idade_inicio` TINYINT NULL COMMENT '',
  `idade_fim` TINYINT NULL COMMENT '',
  `dose_multipla` TINYINT(1) NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_vacina`, `id_usuario`)  COMMENT '',
  UNIQUE INDEX `id_vacina_UNIQUE` (`id_vacina` ASC)  COMMENT '',
  INDEX `fk_Vacina_Usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Vacina_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bbwatch`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Consulta` (
  `id_consulta` INT NOT NULL COMMENT '',
  `data_consulta` VARCHAR(45) NULL COMMENT '',
  `retorno` TINYINT(1) NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  `id_crianca` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_consulta`, `id_usuario`, `id_crianca`)  COMMENT '',
  UNIQUE INDEX `id_consulta_UNIQUE` (`id_consulta` ASC)  COMMENT '',
  INDEX `fk_Consulta_Usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_Consulta_Crianca1_idx` (`id_crianca` ASC)  COMMENT '',
  CONSTRAINT `fk_Consulta_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bbwatch`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Crianca`
    FOREIGN KEY (`id_crianca`)
    REFERENCES `bbwatch`.`Crianca` (`id_crianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Exame` (
  `id_exame` INT NOT NULL COMMENT '',
  `pedido` VARCHAR(300) NULL COMMENT '',
  `digitalizacao` VARCHAR(300) NULL COMMENT '',
  `realizado` TINYINT(1) NULL COMMENT '',
  `data_pedido` DATETIME NULL COMMENT '',
  `data_reaizado` DATETIME NULL COMMENT '',
  `preparo` VARCHAR(300) NULL COMMENT '',
  `observacao` VARCHAR(100) NULL COMMENT '',
  `id_crianca` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_exame`, `id_crianca`)  COMMENT '',
  INDEX `fk_Exame_Crianca1_idx` (`id_crianca` ASC)  COMMENT '',
  CONSTRAINT `fk_Exame_Crianca1`
    FOREIGN KEY (`id_crianca`)
    REFERENCES `bbwatch`.`Crianca` (`id_crianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Medicamento` (
  `id_medicamento` INT NOT NULL COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `data_cadastro` DATETIME NULL COMMENT '',
  `tipo` VARCHAR(10) NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_medicamento`, `id_usuario`)  COMMENT '',
  UNIQUE INDEX `id_medicamento_UNIQUE` (`id_medicamento` ASC)  COMMENT '',
  INDEX `fk_Medicamento_Usuario1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Medicamento_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bbwatch`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Dose_Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Dose_Medicamento` (
  `id_dose` INT NOT NULL COMMENT '',
  `quantidade` DECIMAL NULL COMMENT '',
  `medida` VARCHAR(45) NULL COMMENT '',
  `id_medicamento` INT NOT NULL COMMENT '',
  `id_crianca` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_dose`, `id_medicamento`, `id_crianca`)  COMMENT '',
  INDEX `fk_Dose_Medicamento1_idx` (`id_medicamento` ASC)  COMMENT '',
  INDEX `fk_Dose_Crianca1_idx` (`id_crianca` ASC)  COMMENT '',
  CONSTRAINT `fk_Dose_Medicamento`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `bbwatch`.`Medicamento` (`id_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dose_Crianca`
    FOREIGN KEY (`id_crianca`)
    REFERENCES `bbwatch`.`Crianca` (`id_crianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Aplicacao_Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Aplicacao_Vacina` (
  `id_vacina` INT NOT NULL COMMENT '',
  `id_crianca` INT NOT NULL COMMENT '',
  `data_aplicacao` DATETIME NULL COMMENT '',
  `alergia` TINYINT(1) NULL COMMENT '',
  `dose_numero` TINYINT NULL COMMENT '',
  PRIMARY KEY (`id_vacina`, `id_crianca`)  COMMENT '',
  INDEX `fk_Aplicacao_Vacina_Crianca1_idx` (`id_crianca` ASC)  COMMENT '',
  CONSTRAINT `fk_Aplicacao_Vacina_Vacina1`
    FOREIGN KEY (`id_vacina`)
    REFERENCES `bbwatch`.`Vacina` (`id_vacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aplicacao_Vacina_Crianca1`
    FOREIGN KEY (`id_crianca`)
    REFERENCES `bbwatch`.`Crianca` (`id_crianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Notificacao` (
  `id_notificacao` INT NOT NULL COMMENT '',
  `tipo` VARCHAR(30) NOT NULL COMMENT '',
  `data_inicio` DATETIME NOT NULL COMMENT '',
  `data_fim` DATETIME NULL COMMENT '',
  `intervalo_horas` DECIMAL NULL COMMENT '',
  `intervalo_dias` DECIMAL NULL COMMENT '',
  `intervalo_meses` DECIMAL NULL COMMENT '',
  `intervalo_anos` DECIMAL NULL COMMENT '',
  `dia_semana` VARCHAR(10) NULL COMMENT '',
  `dia_mes` TINYINT NULL COMMENT '',
  `horas` DECIMAL NULL COMMENT '',
  `id_consulta` INT NULL COMMENT '',
  `id_exame` INT NULL COMMENT '',
  `id_dose` INT NULL COMMENT '',
  `id_vacina` INT NULL COMMENT '',
  PRIMARY KEY (`id_notificacao`)  COMMENT '',
  UNIQUE INDEX `id_notificacao_UNIQUE` (`id_notificacao` ASC)  COMMENT '',
  INDEX `fk_Notificacao_Consulta1_idx` (`id_consulta` ASC)  COMMENT '',
  INDEX `fk_Notificacao_Exame1_idx` (`id_exame` ASC)  COMMENT '',
  INDEX `fk_Notificacao_Dose_Medicamento1_idx` (`id_dose` ASC)  COMMENT '',
  INDEX `fk_Notificacao_Aplicacao_Vacina1_idx` (`id_vacina` ASC)  COMMENT '',
  CONSTRAINT `fk_Notificacao_Consulta`
    FOREIGN KEY (`id_consulta`)
    REFERENCES `bbwatch`.`Consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacao_Exame`
    FOREIGN KEY (`id_exame`)
    REFERENCES `bbwatch`.`Exame` (`id_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacao_Dose_Medicamento`
    FOREIGN KEY (`id_dose`)
    REFERENCES `bbwatch`.`Dose_Medicamento` (`id_dose`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacao_Aplicacao_Vacina`
    FOREIGN KEY (`id_vacina`)
    REFERENCES `bbwatch`.`Aplicacao_Vacina` (`id_vacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bbwatch`.`Perfil_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bbwatch`.`Perfil_Usuario` (
  `id_usuario` INT NOT NULL COMMENT '',
  `id_perfil` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`, `id_perfil`)  COMMENT '',
  INDEX `fk_Perfil_Usuario_Perfil1_idx` (`id_perfil` ASC)  COMMENT '',
  CONSTRAINT `fk_Perfil_Usuario_Usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bbwatch`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_Usuario_Perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `bbwatch`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
